language: java

install: true

jdk:
  - openjdk8

notifications:
  email: false

script:
  - export TZ=Asia/Shanghai
  - mvn install -DskipTests=true
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t c590f330-6d1e-4baf-9cbe-e376c11cd96f